config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :themes
  resources :lessons
  resources :articles
  devise_for :users
  root to: 'pages#home'
  get '/admin', to: 'pages#admin'
  get '/voidcamp', to: 'pages#voidcamp'
  get '/contact', to: 'pages#contact'
  get '/community', to: 'pages#community'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :subjects
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy, :index]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:title)
    end
end

app/views/themes/_form.html.erb
<%= simple_form_for(@theme) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-dark"%>
  </div>
<% end %>

app/views/themes/edit.html.erb
<div class="container" style="padding-top: 150px;">

<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>
</div>

app/views/themes/index.html.erb
<div class="container space" style="">
  <h2>Temas</h2>
  <hr>
  <br>
  <% @themes.each do |theme| %>
  <div type="button" data-toggle="collapse" data-target="#demo<%= theme.id%>">
    <h3><%= theme.title %> <i class="fas fa-caret-down"></i></h3>
  </div>
  <br>
  <% theme.subjects.each do |subject| %>
  <div id="demo<%= theme.id%>" class="collapse">
    <%= link_to subject_path(subject) do %>
    <div class="card-category text-center " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path subject.photo.key%>')">
      <br>
      <div style=""></div>
      <h5>· <%= subject.theme.title%></h5>
      <h1><%= subject.title%></h1>
      <h6><%= subject.info %></h6>
      <br>
    </div>
    <% end %>
  </div>
  <% end %>
  <% end %>
  <br>
  <div type="button" data-toggle="collapse" data-target="#demo3">
    <h3>Diseño <i class="fas fa-caret-down"></i></h3>
  </div>
  <br>
  <div id="demo3" class="collapse">
    <h2 class="text-center">Comming soon</h2>
  </div>
  <br>
    <div type="button" data-toggle="collapse" data-target="#demo2">
    <h3>Musica <i class="fas fa-caret-down"></i></h3>
  </div>
  <br>
  <div id="demo2" class="collapse">
    <h2 class="text-center">Comming soon</h2>
  </div>
  <br>
  <div type="button" data-toggle="collapse" data-target="#demo4">
    <h3>Fotografia y Video <i class="fas fa-caret-down"></i></h3>
  </div>
  <br>
  <div id="demo4" class="collapse">
    <h2 class="text-center">Comming soon</h2>
  </div>
  <br>
</div>

app/views/themes/new.html.erb
<div class="container" style="padding-top: 150px;">

<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>
</div>

app/views/themes/show.html.erb
<div class="container" style="padding-top: 150px;">

<p id="notice"><%= notice %></p>
<h1>Themes</h1>
<hr>
<br>
<p>
  <strong>Title:</strong>
  <%= @theme.title %> -
  <%= @theme.lessons %> -
  <%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>
</p>


</div>