config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :themes
  resources :lessons
  resources :articles
  devise_for :users
  root to: 'pages#home'
  get '/admin', to: 'pages#admin'
  get '/voidcamp', to: 'pages#voidcamp'
  get '/contact', to: 'pages#contact'
  get '/community', to: 'pages#community'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner" style="/*background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.7) 50%), url('https://i.pinimg.com/originals/83/6c/c0/836cc0950f630aa6ec7f4481ebfdcea7.gif')*/; background-color: black;">
  <div>
    <div class="hidden-xs hidden-sm">
      <%= image_tag("vclogo.png")%>
    </div>
    <br>
    <p>APRENDE</p>
    <br>
    <i class="fa fa-angle-double-down symbols" aria-hidden="true"></i>

  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="space">
  <div class="footer2">
    <div class="container text-center " style="padding-top: 8px; padding-bottom: 8px;" >
      <a href="http://www.leonardoluxburg.com">
        <%= image_tag "lllogo.png" %>
      </a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon fixed-top">
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "vclogonav.gif" %>
  <% end %>
  <div class="dropdown ">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
     <li> <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link"%> </li>
     <li> <%= link_to "Lecturas", lessons_path, class: "navbar-wagon-item navbar-wagon-link"%> </li>
     <li> <%= link_to "Comunidad", community_path, class: "navbar-wagon-item navbar-wagon-link"%> </li>
     <li> <%= link_to "Contacto", contact_path, class: "navbar-wagon-item navbar-wagon-link"%> </li>
    </ul>
  </div>
</div>

app/views/shared/_slack.html.erb
<div class="text-center">
  <br>
<img src="https://clipartart.com/images/slack-logo-clipart-transparent-2.png" alt="" height="60px">
<br>
<br>
<p>¡Unete a nuestro canal de slack! Por allí podremos responder cualquier pregunta que tengas sobre las lecturas o el proyecto.  También encontraras personas aprendiendo y compartiendo de lo mismo. Queremos poder unir a todos nuestros lectores en un espacio donde puedan compartir sus opiniones y se ayuden a crecer unos a otros. ¡Aprovecha y comparte tus ideas te podrías un topar con un equipo que te ayude a desarrollarla !</p>
  <a href="https://join.slack.com/t/voidcamp/shared_invite/zt-d0os541d-Va~ccbQ9gorA5wzU3wgTzA" target="_blank"><h6 class="btn btn-dark ">
  JOIN NOW</h6></a>
</div>

</div>