config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :themes
  resources :lessons
  resources :articles
  devise_for :users
  root to: 'pages#home'
  get '/admin', to: 'pages#admin'
  get '/voidcamp', to: 'pages#voidcamp'
  get '/contact', to: 'pages#contact'
  get '/community', to: 'pages#community'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/admin.html.erb
<div class="container space" style="">
  <h2 class="">Admin</h2>
  <hr>
  <br>
  <h4>Users - #<%= @users.count %> </h4>
  <br>
  <h4>Temas</h4>
  <% @subjects.each do |subject| %>
  <p><%= subject.title %> - <%= link_to 'Show', subject %> | <%= link_to 'Edit', edit_subject_path(subject) %> | <%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
  <br>
  <%= link_to 'New Subject', new_subject_path %>
  <br>
  <br>
  <h4>Lecturas</h4>
  <% @lessons.each do |lesson| %>
  <p class="card-title"><%= lesson.title%> - <%= link_to 'Show', lesson %> | <%= link_to 'Edit', edit_lesson_path(lesson) %> | <%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
  <%= link_to 'New Lesson', new_lesson_path %>
</div>
</div>
</div>

app/views/pages/community.html.erb
<div class="container" style="padding-top: 150px;">
  <h2 class="">Comunidad</h2>
  <hr>
  <br>
  <br>
  <br>
  <div class="container">
    <div class="row ">
      <div class="col-xs-12 col-md-3 text-center">
        <a href="https://www.twicth.com/voidcamp/" target="_blank"><h1><i class="fab fa-twitch" style="font-size: 60px;"></i></h1></a>
      </div>
      <div class="col-xs-12 col-md-3 text-center">
       <a href="https://www.instagram.com/voidcamp/" target="_blank"> <h1><i class="fab fa-instagram" style="font-size: 60px;"></i></h1></a>
     </div>
     <div class="col-xs-12 col-md-3 text-center">
       <a href="https://www.twitter.com/voidcamp/" target="_blank"> <h1><i class="fab fa-twitter" style="font-size: 60px;"></i></h1> </a>
     </div>
     <div class="col-xs-12 col-md-3 text-center">
       <a href="https://www.youtube.com/voidcamp/" target="_blank"> <h1><i class="fab fa-youtube" style="font-size: 60px;"></i></h1> </a>
     </div>
   </div>
 </div>
 <br>
 <%= render 'shared/slack' %>
</div>
<br>
<br>
<div class="container text-center">
  <h2 style="font-size: 40px"><i class="fab fa-patreon"></i> | PATREON</h2></a>
<p>Si deseas contribuir con el proyecto y recibir beneficios al mismo tiempo suscríbete a nuestro Patreon. Escoge la membresía que más te guste y ayudanos a cumplir el objetivo de Void Camp.</p>
<a href="https://www.patreon.com" target="_blank"><h6 class="btn btn-dark ">
  JOIN NOW</h6></a>
</div>

app/views/pages/contact.html.erb
<div class="container" style=" height: 80vh;
  display: flex;
  align-items: center;
  justify-content: center;
  position:relative;
  background-position: center;
  padding-top:100px;">
<div class="card mb-3" style="">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= image_tag "vcpic.png", class: "card-img"%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h2 class="card-title">Void Camp</h2>
        <hr>
        <div style="padding-left: 10px;">
        <p class=""><i class="fas fa-location-arrow"></i> Ciudad de Panamá, Panamá</p>
        <p class=""><i class="fas fa-mobile-alt"></i> +507 6288-3330</p>
        <p class=""><i class="fas fa-envelope-open-text"></i> projectvoidcamp@gmail.com</p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<br>
<div class="space">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6" >
        <h3>APRENDE · COMPARTE ·  DESARROLLA </h3>
        <p style=" text-align: justify; text-justify: inter-word;">Void Camp es un proyecto que fue creado con la iniciativa de compartir conocimiento, pensamientos y habilidades. Nuestra idea se basa en generar contenido educativo que guie el aprendizaje y el emprendimiento en el mundo digital. Queremos servir como un canal de educación alternativa para cualquiera que desee aprender pero no sepa como empezar. </p><br>
        <a href="/lessons"> <h1 class="button " >Descrubre</h1></a>
      </div>
      <div class="col-sm-12 col-md-6 text-center">
        <div class="" style="padding-top: 30px;">
          <img src="https://www.freepnglogos.com/uploads/macbook-png/macbook-cleanmymac-the-best-mac-cleanup-app-for-macos-get-32.png" alt="" class="responsive">
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<div class="container space" style="">
  <h2 class="">Ultimas Lecturas</h2>
  <hr>
  <br>
  <div class="row">
    <div class="card-deck">
      <% @lessons.each do |lesson| %>
      <div class="col-xs-12 col-md-4">
        <%= link_to lesson_path(lesson) do %>
        <div class="card">
          <img src="<%= cl_image_path lesson.photo.key%>" class="card-img-top" alt="">
          <div class="card-body">
            <h5 class="card-title"><%= lesson.title%></h5>
            <p class="card-text"><%= lesson.intro%></p>
          </div>
          <div class="card-footer">
            <small class="text-muted"><%= lesson.created_at %></small>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<div class="space">
<div style="padding-top: 100px; padding-bottom: 100px; background-color: black;">
  <div class="container">
    <div class="text-center">
      <hr style="background-color: white;">
      <iframe width="100%" height="570" src="https://www.youtube.com/embed/NGXp6_-nc4s?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <br>
      <hr style="background-color: white;">
    </div>
  </div>
</div>
</div>
<br>
<br>
<div>
 <div class="container">
  <div class="space" style="">
    <br>
    <h2 class="text-center">Se parte de Void Camp</h2>
    <p class="text-center">Si deseas obtener más información sobre Void Camp unete a nuestro canal de slack y suscríbete a nuestras redes sociales.</p>
    <div class="text-center">
   <a href="/community"> <button class="buttonv2 ">Unete a nuestra comunidad</button> </a>
    </div>
  </div>
  <br>
</div>
<br>
<br>

app/views/pages/voidcamp.html.erb
<div class="container space" style="">
  <h2 class="">Void Camp</h2>
  <hr>
  <br>
</div>
<div class="container text-justify" style="">
  <p>Void Camp es un proyecto que fue creado con la iniciativa de compartir conocimiento, pensamientos y habilidades. Nuestra idea se basa en crear contenido educativo que pueda guiar el aprendizaje y el emprendimiento en el mundo digital. Queremos poder servir como un canal de educación alternativa para todo aquel desee aprender pero no sepa por donde empezar.
  </p>

</div>
<div class="container text-center">
  <h3 style="padding-top:150px;">Void Camp no seria posible sin la ayuda y <br>  generosidad de amigos como ... </h3>
  <br>
  <div class=" text-center">
    <h5>Si deseas patrocionar Void Camp <strong>contactanos!</strong></h5>
  </div>
  <br>
</div>