config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :themes
  resources :lessons
  resources :articles
  devise_for :users
  root to: 'pages#home'
  get '/admin', to: 'pages#admin'
  get '/voidcamp', to: 'pages#voidcamp'
  get '/contact', to: 'pages#contact'
  get '/community', to: 'pages#community'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :theme
  has_many :lessons
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subjects = Subject.all
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:title, :info, :theme_id)
    end
end

app/views/subjects/_form.html.erb
<%= simple_form_for(@subject) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :info %>
    <%= f.association :theme %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<div class="container" style="padding-top: 150px;">

<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>
</div>

app/views/subjects/index.html.erb
<div class="container" style="padding-top: 150px;">

<p id="notice"><%= notice %></p>

<h1>Subjects</h1>
<hr>
    <% @subjects.each do |subject| %>
        <h3><%= subject.id %></h3>
        <p><%= subject.title %></p>
        <p><%= subject.info %></p>
        <p><%= subject.theme.title %></p>
        <p><%= link_to 'Show', subject %> | <%= link_to 'Edit', edit_subject_path(subject) %> | <%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></p>

    <% end %>

<br>

<%= link_to 'New Subject', new_subject_path %>
</div>

app/views/subjects/new.html.erb
<div class="container" style="padding-top: 150px;">

<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>
</div>

app/views/subjects/show.html.erb
<div class="container space">
<h2><%= @subject.title %></h2>
<hr>
<div class="dropdown">
  <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown">
   Filtrar
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="/lessons">Todas</a>
    <% @subjects.each do |subject| %>
    <%= link_to subject_path(subject) do %>
    <p class="dropdown-item" href="/lessons"><%= subject.title %></p>
    <% end %>
    <% end %>
  </div>
</div>
<br>
  <div class="row">
    <div class="card-deck">
      <% @subject.lessons.each do |lesson| %>
      <div class="col-xs-12 col-md-4">
        <%= link_to lesson_path(lesson) do %>
        <div class="card">
          <img src="<%= cl_image_path lesson.photo.key%>" class="card-img-top" alt="">
          <div class="card-body">
            <h5 class="card-title"><%= lesson.title%></h5>
            <p class="card-text"><%= lesson.intro%></p>
          </div>
          <div class="card-footer">
            <small class="text-muted"><%= lesson.created_at %></small>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>